version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@9.3.6 # Use the AWS ECR orb in your configuration
  aws-cli: circleci/aws-cli@5.1.1 # Use the AWS CLI orb in your configuration
  aws-eks: circleci/aws-eks@2.2.0
  kubernetes: circleci/kubernetes@1.3



workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build_and_push_image: # Use the pre-defined `build-and-push-image` job
          auth:
            - aws-cli/setup:
                role_arn: arn:aws:iam::213561109591:role/CircleCI_Access
          dockerfile: Dockerfile
          path: .
          profile_name: default
          repo: my_registry
          tag: latest # default - latest
      - create-deployment:
          docker:
            - image: cimg/python:3.10
          parameters:
            cluster-name:
              description: |
                my_cluster
              type: string
          steps:
            - checkout
            - aws-eks/update-kubeconfig-with-authenticator:
              cluster-name: my_cluster
              install-kubectl: true
            - kubernetes/create-or-update-resource:
                get-rollout-status: true
                resource-file-path: manifests/deployment.yaml
                resource-name: deployment/code2cloud-python-flask-webserver-deployment
