version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@9.3.6 # Use the AWS ECR orb in your configuration
  aws-cli: circleci/aws-cli@5.1.1 # Use the AWS CLI orb in your configuration
  aws-eks: circleci/aws-eks@2.2.0
  kubernetes: circleci/kubernetes@1.3
jobs:
  build_and_push_image:
    steps:
      - aws-ecr/build_and_push_image: # Use the pre-defined `build-and-push-image` job
          auth:
            - aws-cli/setup:
                role_arn: arn:aws:iam::213561109591:role/CircleCI_Access
          dockerfile: Dockerfile
          path: .
          profile_name: default
          repo: my_registry
          tag: latest # default - latest
  deploy_to_production:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Deploy to EKS
          command: |
              curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
              chmod +x ./kubectl
              pip3 install awscli --upgrade
              aws --version
              aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 213561109591.dkr.ecr.us-east-1.amazonaws.com
              aws eks update-kubeconfig --name my-cluster
              LATEST_SHA=$(git rev-parse HEAD)
              docker build -t code2cloud:$LATEST_SHA .
              docker tag code2cloud:$LATEST_SHA 213561109591.dkr.ecr.us-east-1.amazonaws.com/code2cloud:$LATEST_SHA
              docker push 213561109591.dkr.ecr.us-east-1.amazonaws.com/code2cloud:$LATEST_SHA
              docker tag code2cloud:$LATEST_SHA 213561109591.dkr.ecr.us-east-1.amazonaws.com/code2cloud:latest
              docker push 213561109591.dkr.ecr.us-east-1.amazonaws.com/code2cloud:latest
              ./kubectl set image manifests/code2cloud-python-flask-webserver-deployment code2cloud-python-flask-webserver-deployment=213561109591.dkr.ecr.us-east-1.amazonaws.com/code2cloud:$LATEST_SHA -n default 
workflows:
  - build_push_and_deploy:
    jobs:
      - build_and_push_image
      - deploy_to_production:
        requires: 
          - build_and_push_image

